name = "riza-payment-worker"
main = "src/index.js"
compatibility_date = "2024-03-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
PHONEPE_MERCHANT_ID = "SU2607021907023290314208"
PHONEPE_ENV = "production"
PHONEPE_SALT_INDEX = "1"
# FRONTEND_URL is used to validate client origins for CORS
FRONTEND_URL = "https://rizafashions.in"
