name = "riza-payment-worker"
main = "src/index.js"
compatibility_date = "2024-03-01"
compatibility_flags = [ "nodejs_compat" ]

[vars]
PHONEPE_MERCHANT_ID = "M22K7V5N55588_2607011549"
PHONEPE_ENV = "production"
# FRONTEND_URL is used to validate client origins for CORS
FRONTEND_URL = "https://riza-fashions-c2d77.web.app"
